#!/usr/bin/python3
import os
import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--solver", type=str)
parser.add_argument('-i', '--instance', type=str)
parser.add_argument('-p', '--processes',type=int)

def get_arguments():
    args = parser.parse_args()
    main_args = {}
    if not args.solver is None:
        main_args['solver_name'] = args.solver 
    if not args.instance is None:
        main_args['inst'] = args.instance 
    if not args.processes is None:
        main_args['p'] = args.processes 
    return main_args

def main(solver_name:'str' = 'cp', inst:'str'="07", p:'int'=1):
    instance = 'instances/parsed_instances/'
    if solver_name == 'cp':
        instance += f'cp/inst{inst}.dzn'
        subprocess.run([f'minizinc', '--solver','Gecode', './models/Cp_model.mzn', f'{instance}','-s', '-p',f'{p}','--time-limit', '300000','-i'])
        
if __name__ == '__main__':

    args = get_arguments()
    main(**args) 
