* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 57
*   Variables        : 43
*     Binary         : 32
*     Integer        : 11
*     Continuous     : 0
NAME          
ROWS
 N  COST
 L  auto_c_000000000
 G  auto_c_000000001
 G  auto_c_000000002
 G  auto_c_000000003
 E  auto_c_000000004
 E  auto_c_000000005
 E  auto_c_000000006
 E  auto_c_000000007
 E  auto_c_000000008
 E  auto_c_000000009
 E  auto_c_000000010
 E  auto_c_000000011
 E  auto_c_000000012
 E  auto_c_000000013
 E  auto_c_000000014
 E  auto_c_000000015
 E  auto_c_000000016
 E  auto_c_000000017
 E  auto_c_000000018
 E  auto_c_000000019
 E  auto_c_000000020
 E  auto_c_000000021
 E  auto_c_000000022
 E  auto_c_000000023
 E  auto_c_000000024
 L  auto_c_000000025
 G  auto_c_000000026
 L  auto_c_000000027
 E  auto_c_000000028
 E  auto_c_000000029
 L  auto_c_000000030
 G  auto_c_000000031
 L  auto_c_000000032
 L  auto_c_000000033
 L  auto_c_000000034
 L  auto_c_000000035
 L  auto_c_000000036
 L  auto_c_000000037
 L  auto_c_000000038
 L  auto_c_000000039
 L  auto_c_000000040
 L  auto_c_000000041
 L  auto_c_000000042
 L  auto_c_000000043
 L  auto_c_000000044
 G  auto_c_000000045
 G  auto_c_000000046
 G  auto_c_000000047
 G  auto_c_000000048
 G  auto_c_000000049
 G  auto_c_000000050
 G  auto_c_000000051
 G  auto_c_000000052
 G  auto_c_000000053
 G  auto_c_000000054
 G  auto_c_000000055
 G  auto_c_000000056
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    table_0_0_0         auto_c_000000004         1  auto_c_000000020         1
    table_0_0_0         auto_c_000000025        20  auto_c_000000026         1
    table_0_0_0         auto_c_000000027         1
    table_0_0_1         auto_c_000000002       -21  auto_c_000000005         1
    table_0_0_1         auto_c_000000009        -1  auto_c_000000021         1
    table_0_0_1         auto_c_000000025        17  auto_c_000000026         1
    table_0_0_1         auto_c_000000027         1  auto_c_000000033         1
    table_0_0_1         auto_c_000000035         1  auto_c_000000045        -4
    table_0_0_2         auto_c_000000002       -86  auto_c_000000005         1
    table_0_0_2         auto_c_000000013        -1  auto_c_000000022         1
    table_0_0_2         auto_c_000000025         6  auto_c_000000026         1
    table_0_0_2         auto_c_000000027         1  auto_c_000000034         1
    table_0_0_2         auto_c_000000037         1  auto_c_000000046        -4
    table_0_0_3         auto_c_000000002       -99  auto_c_000000005         1
    table_0_0_3         auto_c_000000017        -1  auto_c_000000024         1
    table_0_1_0         auto_c_000000002       -21  auto_c_000000005        -1
    table_0_1_0         auto_c_000000009         1  auto_c_000000020         1
    table_0_1_0         auto_c_000000025        20  auto_c_000000026         1
    table_0_1_0         auto_c_000000027         1  auto_c_000000033         1
    table_0_1_0         auto_c_000000035         1  auto_c_000000047        -4
    table_0_1_1         auto_c_000000008         1  auto_c_000000021         1
    table_0_1_1         auto_c_000000025        17  auto_c_000000026         1
    table_0_1_1         auto_c_000000027         1
    table_0_1_2         auto_c_000000002       -71  auto_c_000000009         1
    table_0_1_2         auto_c_000000013        -1  auto_c_000000022         1
    table_0_1_2         auto_c_000000025         6  auto_c_000000026         1
    table_0_1_2         auto_c_000000027         1  auto_c_000000036         1
    table_0_1_2         auto_c_000000038         1  auto_c_000000048        -4
    table_0_1_3         auto_c_000000002       -80  auto_c_000000009         1
    table_0_1_3         auto_c_000000017        -1  auto_c_000000024         1
    table_0_2_0         auto_c_000000002       -92  auto_c_000000005        -1
    table_0_2_0         auto_c_000000013         1  auto_c_000000020         1
    table_0_2_0         auto_c_000000025        20  auto_c_000000026         1
    table_0_2_0         auto_c_000000027         1  auto_c_000000034         1
    table_0_2_0         auto_c_000000037         1  auto_c_000000049        -4
    table_0_2_1         auto_c_000000002       -71  auto_c_000000009        -1
    table_0_2_1         auto_c_000000013         1  auto_c_000000021         1
    table_0_2_1         auto_c_000000025        17  auto_c_000000026         1
    table_0_2_1         auto_c_000000027         1  auto_c_000000036         1
    table_0_2_1         auto_c_000000038         1  auto_c_000000050        -4
    table_0_2_2         auto_c_000000012         1  auto_c_000000022         1
    table_0_2_2         auto_c_000000025         6  auto_c_000000026         1
    table_0_2_2         auto_c_000000027         1
    table_0_2_3         auto_c_000000002       -61  auto_c_000000013         1
    table_0_2_3         auto_c_000000017        -1  auto_c_000000024         1
    table_0_3_0         auto_c_000000002       -59  auto_c_000000005        -1
    table_0_3_0         auto_c_000000017         1  auto_c_000000020         1
    table_0_3_0         auto_c_000000023         1  auto_c_000000025        20
    table_0_3_0         auto_c_000000026         1  auto_c_000000027         1
    table_0_3_1         auto_c_000000002       -80  auto_c_000000009        -1
    table_0_3_1         auto_c_000000017         1  auto_c_000000021         1
    table_0_3_1         auto_c_000000023         1  auto_c_000000025        17
    table_0_3_1         auto_c_000000026         1  auto_c_000000027         1
    table_0_3_2         auto_c_000000002       -61  auto_c_000000013        -1
    table_0_3_2         auto_c_000000017         1  auto_c_000000022         1
    table_0_3_2         auto_c_000000023         1  auto_c_000000025         6
    table_0_3_2         auto_c_000000026         1  auto_c_000000027         1
    table_0_3_3         auto_c_000000016         1
    table_1_0_0         auto_c_000000006         1  auto_c_000000020         1
    table_1_0_0         auto_c_000000030        20  auto_c_000000031         1
    table_1_0_0         auto_c_000000032         1
    table_1_0_1         auto_c_000000003       -21  auto_c_000000007         1
    table_1_0_1         auto_c_000000011        -1  auto_c_000000021         1
    table_1_0_1         auto_c_000000030        17  auto_c_000000031         1
    table_1_0_1         auto_c_000000032         1  auto_c_000000039         1
    table_1_0_1         auto_c_000000041         1  auto_c_000000051        -4
    table_1_0_2         auto_c_000000003       -86  auto_c_000000007         1
    table_1_0_2         auto_c_000000015        -1  auto_c_000000022         1
    table_1_0_2         auto_c_000000030         6  auto_c_000000031         1
    table_1_0_2         auto_c_000000032         1  auto_c_000000040         1
    table_1_0_2         auto_c_000000043         1  auto_c_000000052        -4
    table_1_0_3         auto_c_000000003       -99  auto_c_000000007         1
    table_1_0_3         auto_c_000000019        -1  auto_c_000000029         1
    table_1_1_0         auto_c_000000003       -21  auto_c_000000007        -1
    table_1_1_0         auto_c_000000011         1  auto_c_000000020         1
    table_1_1_0         auto_c_000000030        20  auto_c_000000031         1
    table_1_1_0         auto_c_000000032         1  auto_c_000000039         1
    table_1_1_0         auto_c_000000041         1  auto_c_000000053        -4
    table_1_1_1         auto_c_000000010         1  auto_c_000000021         1
    table_1_1_1         auto_c_000000030        17  auto_c_000000031         1
    table_1_1_1         auto_c_000000032         1
    table_1_1_2         auto_c_000000003       -71  auto_c_000000011         1
    table_1_1_2         auto_c_000000015        -1  auto_c_000000022         1
    table_1_1_2         auto_c_000000030         6  auto_c_000000031         1
    table_1_1_2         auto_c_000000032         1  auto_c_000000042         1
    table_1_1_2         auto_c_000000044         1  auto_c_000000054        -4
    table_1_1_3         auto_c_000000003       -80  auto_c_000000011         1
    table_1_1_3         auto_c_000000019        -1  auto_c_000000029         1
    table_1_2_0         auto_c_000000003       -92  auto_c_000000007        -1
    table_1_2_0         auto_c_000000015         1  auto_c_000000020         1
    table_1_2_0         auto_c_000000030        20  auto_c_000000031         1
    table_1_2_0         auto_c_000000032         1  auto_c_000000040         1
    table_1_2_0         auto_c_000000043         1  auto_c_000000055        -4
    table_1_2_1         auto_c_000000003       -71  auto_c_000000011        -1
    table_1_2_1         auto_c_000000015         1  auto_c_000000021         1
    table_1_2_1         auto_c_000000030        17  auto_c_000000031         1
    table_1_2_1         auto_c_000000032         1  auto_c_000000042         1
    table_1_2_1         auto_c_000000044         1  auto_c_000000056        -4
    table_1_2_2         auto_c_000000014         1  auto_c_000000022         1
    table_1_2_2         auto_c_000000030         6  auto_c_000000031         1
    table_1_2_2         auto_c_000000032         1
    table_1_2_3         auto_c_000000003       -61  auto_c_000000015         1
    table_1_2_3         auto_c_000000019        -1  auto_c_000000029         1
    table_1_3_0         auto_c_000000003       -59  auto_c_000000007        -1
    table_1_3_0         auto_c_000000019         1  auto_c_000000020         1
    table_1_3_0         auto_c_000000028         1  auto_c_000000030        20
    table_1_3_0         auto_c_000000031         1  auto_c_000000032         1
    table_1_3_1         auto_c_000000003       -80  auto_c_000000011        -1
    table_1_3_1         auto_c_000000019         1  auto_c_000000021         1
    table_1_3_1         auto_c_000000028         1  auto_c_000000030        17
    table_1_3_1         auto_c_000000031         1  auto_c_000000032         1
    table_1_3_2         auto_c_000000003       -61  auto_c_000000015        -1
    table_1_3_2         auto_c_000000019         1  auto_c_000000022         1
    table_1_3_2         auto_c_000000028         1  auto_c_000000030         6
    table_1_3_2         auto_c_000000031         1  auto_c_000000032         1
    table_1_3_3         auto_c_000000018         1
    u_0_0               auto_c_000000045        -1  auto_c_000000046        -1
    u_0_0               auto_c_000000047         1  auto_c_000000049         1
    u_0_1               auto_c_000000045         1  auto_c_000000047        -1
    u_0_1               auto_c_000000048        -1  auto_c_000000050         1
    u_0_2               auto_c_000000046         1  auto_c_000000048         1
    u_0_2               auto_c_000000049        -1  auto_c_000000050        -1
    u_1_0               auto_c_000000051        -1  auto_c_000000052        -1
    u_1_0               auto_c_000000053         1  auto_c_000000055         1
    u_1_1               auto_c_000000051         1  auto_c_000000053        -1
    u_1_1               auto_c_000000054        -1  auto_c_000000056         1
    u_1_2               auto_c_000000052         1  auto_c_000000054         1
    u_1_2               auto_c_000000055        -1  auto_c_000000056        -1
    obj                 COST                     1  auto_c_000000000         1
    obj                 auto_c_000000001         1  auto_c_000000002         1
    obj                 auto_c_000000003         1
  INTEND    'MARKER'                            'INTEND'
RHS
    RHS                 auto_c_000000000       342  auto_c_000000001       160
    RHS                 auto_c_000000002         0  auto_c_000000003         0
    RHS                 auto_c_000000004         0  auto_c_000000005         0
    RHS                 auto_c_000000006         0  auto_c_000000007         0
    RHS                 auto_c_000000008         0  auto_c_000000009         0
    RHS                 auto_c_000000010         0  auto_c_000000011         0
    RHS                 auto_c_000000012         0  auto_c_000000013         0
    RHS                 auto_c_000000014         0  auto_c_000000015         0
    RHS                 auto_c_000000016         0  auto_c_000000017         0
    RHS                 auto_c_000000018         0  auto_c_000000019         0
    RHS                 auto_c_000000020         1  auto_c_000000021         1
    RHS                 auto_c_000000022         1  auto_c_000000023         1
    RHS                 auto_c_000000024         1  auto_c_000000025        18
    RHS                 auto_c_000000026         1  auto_c_000000027       342
    RHS                 auto_c_000000028         1  auto_c_000000029         1
    RHS                 auto_c_000000030        30  auto_c_000000031         1
    RHS                 auto_c_000000032       342  auto_c_000000033         1
    RHS                 auto_c_000000034         1  auto_c_000000035         1
    RHS                 auto_c_000000036         1  auto_c_000000037         1
    RHS                 auto_c_000000038         1  auto_c_000000039         1
    RHS                 auto_c_000000040         1  auto_c_000000041         1
    RHS                 auto_c_000000042         1  auto_c_000000043         1
    RHS                 auto_c_000000044         1  auto_c_000000045        -3
    RHS                 auto_c_000000046        -3  auto_c_000000047        -3
    RHS                 auto_c_000000048        -3  auto_c_000000049        -3
    RHS                 auto_c_000000050        -3  auto_c_000000051        -3
    RHS                 auto_c_000000052        -3  auto_c_000000053        -3
    RHS                 auto_c_000000054        -3  auto_c_000000055        -3
    RHS                 auto_c_000000056        -3
BOUNDS
 BV BOUND               table_0_0_0
 BV BOUND               table_0_0_1
 BV BOUND               table_0_0_2
 BV BOUND               table_0_0_3
 BV BOUND               table_0_1_0
 BV BOUND               table_0_1_1
 BV BOUND               table_0_1_2
 BV BOUND               table_0_1_3
 BV BOUND               table_0_2_0
 BV BOUND               table_0_2_1
 BV BOUND               table_0_2_2
 BV BOUND               table_0_2_3
 BV BOUND               table_0_3_0
 BV BOUND               table_0_3_1
 BV BOUND               table_0_3_2
 BV BOUND               table_0_3_3
 BV BOUND               table_1_0_0
 BV BOUND               table_1_0_1
 BV BOUND               table_1_0_2
 BV BOUND               table_1_0_3
 BV BOUND               table_1_1_0
 BV BOUND               table_1_1_1
 BV BOUND               table_1_1_2
 BV BOUND               table_1_1_3
 BV BOUND               table_1_2_0
 BV BOUND               table_1_2_1
 BV BOUND               table_1_2_2
 BV BOUND               table_1_2_3
 BV BOUND               table_1_3_0
 BV BOUND               table_1_3_1
 BV BOUND               table_1_3_2
 BV BOUND               table_1_3_3
 UI BOUND               courier_distance_0     342
 UI BOUND               courier_distance_1     342
 UI BOUND               u_0_0                    3
 UI BOUND               u_0_1                    3
 UI BOUND               u_0_2                    3
 UI BOUND               u_0_3                    3
 UI BOUND               u_1_0                    3
 UI BOUND               u_1_1                    3
 UI BOUND               u_1_2                    3
 UI BOUND               u_1_3                    3
 UI BOUND               obj                    342
ENDATA
