* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 168
*   Variables        : 115
*     Binary         : 98
*     Integer        : 17
*     Continuous     : 0
NAME          
ROWS
 N  COST
 L  auto_c_000000000
 G  auto_c_000000001
 G  auto_c_000000002
 G  auto_c_000000003
 E  auto_c_000000004
 E  auto_c_000000005
 E  auto_c_000000006
 E  auto_c_000000007
 E  auto_c_000000008
 E  auto_c_000000009
 E  auto_c_000000010
 E  auto_c_000000011
 E  auto_c_000000012
 E  auto_c_000000013
 E  auto_c_000000014
 E  auto_c_000000015
 E  auto_c_000000016
 E  auto_c_000000017
 E  auto_c_000000018
 E  auto_c_000000019
 E  auto_c_000000020
 E  auto_c_000000021
 E  auto_c_000000022
 E  auto_c_000000023
 E  auto_c_000000024
 E  auto_c_000000025
 E  auto_c_000000026
 E  auto_c_000000027
 E  auto_c_000000028
 E  auto_c_000000029
 E  auto_c_000000030
 E  auto_c_000000031
 E  auto_c_000000032
 E  auto_c_000000033
 E  auto_c_000000034
 E  auto_c_000000035
 E  auto_c_000000036
 E  auto_c_000000037
 E  auto_c_000000038
 E  auto_c_000000039
 L  auto_c_000000040
 G  auto_c_000000041
 L  auto_c_000000042
 E  auto_c_000000043
 E  auto_c_000000044
 L  auto_c_000000045
 G  auto_c_000000046
 L  auto_c_000000047
 L  auto_c_000000048
 L  auto_c_000000049
 L  auto_c_000000050
 L  auto_c_000000051
 L  auto_c_000000052
 L  auto_c_000000053
 L  auto_c_000000054
 L  auto_c_000000055
 L  auto_c_000000056
 L  auto_c_000000057
 L  auto_c_000000058
 L  auto_c_000000059
 L  auto_c_000000060
 L  auto_c_000000061
 L  auto_c_000000062
 L  auto_c_000000063
 L  auto_c_000000064
 L  auto_c_000000065
 L  auto_c_000000066
 L  auto_c_000000067
 L  auto_c_000000068
 L  auto_c_000000069
 L  auto_c_000000070
 L  auto_c_000000071
 L  auto_c_000000072
 L  auto_c_000000073
 L  auto_c_000000074
 L  auto_c_000000075
 L  auto_c_000000076
 L  auto_c_000000077
 L  auto_c_000000078
 L  auto_c_000000079
 L  auto_c_000000080
 L  auto_c_000000081
 L  auto_c_000000082
 L  auto_c_000000083
 L  auto_c_000000084
 L  auto_c_000000085
 L  auto_c_000000086
 L  auto_c_000000087
 L  auto_c_000000088
 L  auto_c_000000089
 L  auto_c_000000090
 L  auto_c_000000091
 L  auto_c_000000092
 L  auto_c_000000093
 L  auto_c_000000094
 L  auto_c_000000095
 L  auto_c_000000096
 L  auto_c_000000097
 L  auto_c_000000098
 L  auto_c_000000099
 L  auto_c_000000100
 L  auto_c_000000101
 L  auto_c_000000102
 L  auto_c_000000103
 L  auto_c_000000104
 L  auto_c_000000105
 L  auto_c_000000106
 L  auto_c_000000107
 G  auto_c_000000108
 G  auto_c_000000109
 G  auto_c_000000110
 G  auto_c_000000111
 G  auto_c_000000112
 G  auto_c_000000113
 G  auto_c_000000114
 G  auto_c_000000115
 G  auto_c_000000116
 G  auto_c_000000117
 G  auto_c_000000118
 G  auto_c_000000119
 G  auto_c_000000120
 G  auto_c_000000121
 G  auto_c_000000122
 G  auto_c_000000123
 G  auto_c_000000124
 G  auto_c_000000125
 G  auto_c_000000126
 G  auto_c_000000127
 G  auto_c_000000128
 G  auto_c_000000129
 G  auto_c_000000130
 G  auto_c_000000131
 G  auto_c_000000132
 G  auto_c_000000133
 G  auto_c_000000134
 G  auto_c_000000135
 G  auto_c_000000136
 G  auto_c_000000137
 G  auto_c_000000138
 G  auto_c_000000139
 G  auto_c_000000140
 G  auto_c_000000141
 G  auto_c_000000142
 G  auto_c_000000143
 G  auto_c_000000144
 G  auto_c_000000145
 G  auto_c_000000146
 G  auto_c_000000147
 G  auto_c_000000148
 G  auto_c_000000149
 G  auto_c_000000150
 G  auto_c_000000151
 G  auto_c_000000152
 G  auto_c_000000153
 G  auto_c_000000154
 G  auto_c_000000155
 G  auto_c_000000156
 G  auto_c_000000157
 G  auto_c_000000158
 G  auto_c_000000159
 G  auto_c_000000160
 G  auto_c_000000161
 G  auto_c_000000162
 G  auto_c_000000163
 G  auto_c_000000164
 G  auto_c_000000165
 G  auto_c_000000166
 G  auto_c_000000167
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    table_0_0_0         auto_c_000000004         1  auto_c_000000032         1
    table_0_0_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_0_0         auto_c_000000042         1
    table_0_0_1         auto_c_000000002        -3  auto_c_000000005         1
    table_0_0_1         auto_c_000000009        -1  auto_c_000000033         1
    table_0_0_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_0_1         auto_c_000000042         1  auto_c_000000048         1
    table_0_0_1         auto_c_000000053         1  auto_c_000000108        -7
    table_0_0_2         auto_c_000000002        -4  auto_c_000000005         1
    table_0_0_2         auto_c_000000013        -1  auto_c_000000034         1
    table_0_0_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_0_2         auto_c_000000042         1  auto_c_000000049         1
    table_0_0_2         auto_c_000000058         1  auto_c_000000109        -7
    table_0_0_3         auto_c_000000002        -5  auto_c_000000005         1
    table_0_0_3         auto_c_000000017        -1  auto_c_000000035         1
    table_0_0_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_0_3         auto_c_000000042         1  auto_c_000000050         1
    table_0_0_3         auto_c_000000063         1  auto_c_000000110        -7
    table_0_0_4         auto_c_000000002        -6  auto_c_000000005         1
    table_0_0_4         auto_c_000000021        -1  auto_c_000000036         1
    table_0_0_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_0_4         auto_c_000000042         1  auto_c_000000051         1
    table_0_0_4         auto_c_000000068         1  auto_c_000000111        -7
    table_0_0_5         auto_c_000000002        -6  auto_c_000000005         1
    table_0_0_5         auto_c_000000025        -1  auto_c_000000037         1
    table_0_0_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_0_5         auto_c_000000042         1  auto_c_000000052         1
    table_0_0_5         auto_c_000000073         1  auto_c_000000112        -7
    table_0_0_6         auto_c_000000002        -2  auto_c_000000005         1
    table_0_0_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_1_0         auto_c_000000002        -3  auto_c_000000005        -1
    table_0_1_0         auto_c_000000009         1  auto_c_000000032         1
    table_0_1_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_1_0         auto_c_000000042         1  auto_c_000000048         1
    table_0_1_0         auto_c_000000053         1  auto_c_000000113        -7
    table_0_1_1         auto_c_000000008         1  auto_c_000000033         1
    table_0_1_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_1_1         auto_c_000000042         1
    table_0_1_2         auto_c_000000002        -1  auto_c_000000009         1
    table_0_1_2         auto_c_000000013        -1  auto_c_000000034         1
    table_0_1_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_1_2         auto_c_000000042         1  auto_c_000000054         1
    table_0_1_2         auto_c_000000059         1  auto_c_000000114        -7
    table_0_1_3         auto_c_000000002        -4  auto_c_000000009         1
    table_0_1_3         auto_c_000000017        -1  auto_c_000000035         1
    table_0_1_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_1_3         auto_c_000000042         1  auto_c_000000055         1
    table_0_1_3         auto_c_000000064         1  auto_c_000000115        -7
    table_0_1_4         auto_c_000000002        -5  auto_c_000000009         1
    table_0_1_4         auto_c_000000021        -1  auto_c_000000036         1
    table_0_1_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_1_4         auto_c_000000042         1  auto_c_000000056         1
    table_0_1_4         auto_c_000000069         1  auto_c_000000116        -7
    table_0_1_5         auto_c_000000002        -7  auto_c_000000009         1
    table_0_1_5         auto_c_000000025        -1  auto_c_000000037         1
    table_0_1_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_1_5         auto_c_000000042         1  auto_c_000000057         1
    table_0_1_5         auto_c_000000074         1  auto_c_000000117        -7
    table_0_1_6         auto_c_000000002        -3  auto_c_000000009         1
    table_0_1_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_2_0         auto_c_000000002        -4  auto_c_000000005        -1
    table_0_2_0         auto_c_000000013         1  auto_c_000000032         1
    table_0_2_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_2_0         auto_c_000000042         1  auto_c_000000049         1
    table_0_2_0         auto_c_000000058         1  auto_c_000000118        -7
    table_0_2_1         auto_c_000000002        -1  auto_c_000000009        -1
    table_0_2_1         auto_c_000000013         1  auto_c_000000033         1
    table_0_2_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_2_1         auto_c_000000042         1  auto_c_000000054         1
    table_0_2_1         auto_c_000000059         1  auto_c_000000119        -7
    table_0_2_2         auto_c_000000012         1  auto_c_000000034         1
    table_0_2_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_2_2         auto_c_000000042         1
    table_0_2_3         auto_c_000000002        -5  auto_c_000000013         1
    table_0_2_3         auto_c_000000017        -1  auto_c_000000035         1
    table_0_2_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_2_3         auto_c_000000042         1  auto_c_000000060         1
    table_0_2_3         auto_c_000000065         1  auto_c_000000120        -7
    table_0_2_4         auto_c_000000002        -6  auto_c_000000013         1
    table_0_2_4         auto_c_000000021        -1  auto_c_000000036         1
    table_0_2_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_2_4         auto_c_000000042         1  auto_c_000000061         1
    table_0_2_4         auto_c_000000070         1  auto_c_000000121        -7
    table_0_2_5         auto_c_000000002        -6  auto_c_000000013         1
    table_0_2_5         auto_c_000000025        -1  auto_c_000000037         1
    table_0_2_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_2_5         auto_c_000000042         1  auto_c_000000062         1
    table_0_2_5         auto_c_000000075         1  auto_c_000000122        -7
    table_0_2_6         auto_c_000000002        -4  auto_c_000000013         1
    table_0_2_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_3_0         auto_c_000000002        -4  auto_c_000000005        -1
    table_0_3_0         auto_c_000000017         1  auto_c_000000032         1
    table_0_3_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_3_0         auto_c_000000042         1  auto_c_000000050         1
    table_0_3_0         auto_c_000000063         1  auto_c_000000123        -7
    table_0_3_1         auto_c_000000002        -4  auto_c_000000009        -1
    table_0_3_1         auto_c_000000017         1  auto_c_000000033         1
    table_0_3_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_3_1         auto_c_000000042         1  auto_c_000000055         1
    table_0_3_1         auto_c_000000064         1  auto_c_000000124        -7
    table_0_3_2         auto_c_000000002        -5  auto_c_000000013        -1
    table_0_3_2         auto_c_000000017         1  auto_c_000000034         1
    table_0_3_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_3_2         auto_c_000000042         1  auto_c_000000060         1
    table_0_3_2         auto_c_000000065         1  auto_c_000000125        -7
    table_0_3_3         auto_c_000000016         1  auto_c_000000035         1
    table_0_3_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_3_3         auto_c_000000042         1
    table_0_3_4         auto_c_000000002        -3  auto_c_000000017         1
    table_0_3_4         auto_c_000000021        -1  auto_c_000000036         1
    table_0_3_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_3_4         auto_c_000000042         1  auto_c_000000066         1
    table_0_3_4         auto_c_000000071         1  auto_c_000000126        -7
    table_0_3_5         auto_c_000000002        -3  auto_c_000000017         1
    table_0_3_5         auto_c_000000025        -1  auto_c_000000037         1
    table_0_3_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_3_5         auto_c_000000042         1  auto_c_000000067         1
    table_0_3_5         auto_c_000000076         1  auto_c_000000127        -7
    table_0_3_6         auto_c_000000002        -2  auto_c_000000017         1
    table_0_3_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_4_0         auto_c_000000002        -6  auto_c_000000005        -1
    table_0_4_0         auto_c_000000021         1  auto_c_000000032         1
    table_0_4_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_4_0         auto_c_000000042         1  auto_c_000000051         1
    table_0_4_0         auto_c_000000068         1  auto_c_000000128        -7
    table_0_4_1         auto_c_000000002        -7  auto_c_000000009        -1
    table_0_4_1         auto_c_000000021         1  auto_c_000000033         1
    table_0_4_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_4_1         auto_c_000000042         1  auto_c_000000056         1
    table_0_4_1         auto_c_000000069         1  auto_c_000000129        -7
    table_0_4_2         auto_c_000000002        -8  auto_c_000000013        -1
    table_0_4_2         auto_c_000000021         1  auto_c_000000034         1
    table_0_4_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_4_2         auto_c_000000042         1  auto_c_000000061         1
    table_0_4_2         auto_c_000000070         1  auto_c_000000130        -7
    table_0_4_3         auto_c_000000002        -3  auto_c_000000017        -1
    table_0_4_3         auto_c_000000021         1  auto_c_000000035         1
    table_0_4_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_4_3         auto_c_000000042         1  auto_c_000000066         1
    table_0_4_3         auto_c_000000071         1  auto_c_000000131        -7
    table_0_4_4         auto_c_000000020         1  auto_c_000000036         1
    table_0_4_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_4_4         auto_c_000000042         1
    table_0_4_5         auto_c_000000002        -2  auto_c_000000021         1
    table_0_4_5         auto_c_000000025        -1  auto_c_000000037         1
    table_0_4_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_4_5         auto_c_000000042         1  auto_c_000000072         1
    table_0_4_5         auto_c_000000077         1  auto_c_000000132        -7
    table_0_4_6         auto_c_000000002        -4  auto_c_000000021         1
    table_0_4_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_5_0         auto_c_000000002        -6  auto_c_000000005        -1
    table_0_5_0         auto_c_000000025         1  auto_c_000000032         1
    table_0_5_0         auto_c_000000040         3  auto_c_000000041         1
    table_0_5_0         auto_c_000000042         1  auto_c_000000052         1
    table_0_5_0         auto_c_000000073         1  auto_c_000000133        -7
    table_0_5_1         auto_c_000000002        -7  auto_c_000000009        -1
    table_0_5_1         auto_c_000000025         1  auto_c_000000033         1
    table_0_5_1         auto_c_000000040         2  auto_c_000000041         1
    table_0_5_1         auto_c_000000042         1  auto_c_000000057         1
    table_0_5_1         auto_c_000000074         1  auto_c_000000134        -7
    table_0_5_2         auto_c_000000002        -8  auto_c_000000013        -1
    table_0_5_2         auto_c_000000025         1  auto_c_000000034         1
    table_0_5_2         auto_c_000000040         6  auto_c_000000041         1
    table_0_5_2         auto_c_000000042         1  auto_c_000000062         1
    table_0_5_2         auto_c_000000075         1  auto_c_000000135        -7
    table_0_5_3         auto_c_000000002        -3  auto_c_000000017        -1
    table_0_5_3         auto_c_000000025         1  auto_c_000000035         1
    table_0_5_3         auto_c_000000040         5  auto_c_000000041         1
    table_0_5_3         auto_c_000000042         1  auto_c_000000067         1
    table_0_5_3         auto_c_000000076         1  auto_c_000000136        -7
    table_0_5_4         auto_c_000000002        -2  auto_c_000000021        -1
    table_0_5_4         auto_c_000000025         1  auto_c_000000036         1
    table_0_5_4         auto_c_000000040         4  auto_c_000000041         1
    table_0_5_4         auto_c_000000042         1  auto_c_000000072         1
    table_0_5_4         auto_c_000000077         1  auto_c_000000137        -7
    table_0_5_5         auto_c_000000024         1  auto_c_000000037         1
    table_0_5_5         auto_c_000000040         4  auto_c_000000041         1
    table_0_5_5         auto_c_000000042         1
    table_0_5_6         auto_c_000000002        -4  auto_c_000000025         1
    table_0_5_6         auto_c_000000029        -1  auto_c_000000039         1
    table_0_6_0         auto_c_000000002        -2  auto_c_000000005        -1
    table_0_6_0         auto_c_000000029         1  auto_c_000000032         1
    table_0_6_0         auto_c_000000038         1  auto_c_000000040         3
    table_0_6_0         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_1         auto_c_000000002        -3  auto_c_000000009        -1
    table_0_6_1         auto_c_000000029         1  auto_c_000000033         1
    table_0_6_1         auto_c_000000038         1  auto_c_000000040         2
    table_0_6_1         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_2         auto_c_000000002        -4  auto_c_000000013        -1
    table_0_6_2         auto_c_000000029         1  auto_c_000000034         1
    table_0_6_2         auto_c_000000038         1  auto_c_000000040         6
    table_0_6_2         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_3         auto_c_000000002        -3  auto_c_000000017        -1
    table_0_6_3         auto_c_000000029         1  auto_c_000000035         1
    table_0_6_3         auto_c_000000038         1  auto_c_000000040         5
    table_0_6_3         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_4         auto_c_000000002        -4  auto_c_000000021        -1
    table_0_6_4         auto_c_000000029         1  auto_c_000000036         1
    table_0_6_4         auto_c_000000038         1  auto_c_000000040         4
    table_0_6_4         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_5         auto_c_000000002        -4  auto_c_000000025        -1
    table_0_6_5         auto_c_000000029         1  auto_c_000000037         1
    table_0_6_5         auto_c_000000038         1  auto_c_000000040         4
    table_0_6_5         auto_c_000000041         1  auto_c_000000042         1
    table_0_6_6         auto_c_000000028         1
    table_1_0_0         auto_c_000000006         1  auto_c_000000032         1
    table_1_0_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_0_0         auto_c_000000047         1
    table_1_0_1         auto_c_000000003        -3  auto_c_000000007         1
    table_1_0_1         auto_c_000000011        -1  auto_c_000000033         1
    table_1_0_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_0_1         auto_c_000000047         1  auto_c_000000078         1
    table_1_0_1         auto_c_000000083         1  auto_c_000000138        -7
    table_1_0_2         auto_c_000000003        -4  auto_c_000000007         1
    table_1_0_2         auto_c_000000015        -1  auto_c_000000034         1
    table_1_0_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_0_2         auto_c_000000047         1  auto_c_000000079         1
    table_1_0_2         auto_c_000000088         1  auto_c_000000139        -7
    table_1_0_3         auto_c_000000003        -5  auto_c_000000007         1
    table_1_0_3         auto_c_000000019        -1  auto_c_000000035         1
    table_1_0_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_0_3         auto_c_000000047         1  auto_c_000000080         1
    table_1_0_3         auto_c_000000093         1  auto_c_000000140        -7
    table_1_0_4         auto_c_000000003        -6  auto_c_000000007         1
    table_1_0_4         auto_c_000000023        -1  auto_c_000000036         1
    table_1_0_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_0_4         auto_c_000000047         1  auto_c_000000081         1
    table_1_0_4         auto_c_000000098         1  auto_c_000000141        -7
    table_1_0_5         auto_c_000000003        -6  auto_c_000000007         1
    table_1_0_5         auto_c_000000027        -1  auto_c_000000037         1
    table_1_0_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_0_5         auto_c_000000047         1  auto_c_000000082         1
    table_1_0_5         auto_c_000000103         1  auto_c_000000142        -7
    table_1_0_6         auto_c_000000003        -2  auto_c_000000007         1
    table_1_0_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_1_0         auto_c_000000003        -3  auto_c_000000007        -1
    table_1_1_0         auto_c_000000011         1  auto_c_000000032         1
    table_1_1_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_1_0         auto_c_000000047         1  auto_c_000000078         1
    table_1_1_0         auto_c_000000083         1  auto_c_000000143        -7
    table_1_1_1         auto_c_000000010         1  auto_c_000000033         1
    table_1_1_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_1_1         auto_c_000000047         1
    table_1_1_2         auto_c_000000003        -1  auto_c_000000011         1
    table_1_1_2         auto_c_000000015        -1  auto_c_000000034         1
    table_1_1_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_1_2         auto_c_000000047         1  auto_c_000000084         1
    table_1_1_2         auto_c_000000089         1  auto_c_000000144        -7
    table_1_1_3         auto_c_000000003        -4  auto_c_000000011         1
    table_1_1_3         auto_c_000000019        -1  auto_c_000000035         1
    table_1_1_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_1_3         auto_c_000000047         1  auto_c_000000085         1
    table_1_1_3         auto_c_000000094         1  auto_c_000000145        -7
    table_1_1_4         auto_c_000000003        -5  auto_c_000000011         1
    table_1_1_4         auto_c_000000023        -1  auto_c_000000036         1
    table_1_1_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_1_4         auto_c_000000047         1  auto_c_000000086         1
    table_1_1_4         auto_c_000000099         1  auto_c_000000146        -7
    table_1_1_5         auto_c_000000003        -7  auto_c_000000011         1
    table_1_1_5         auto_c_000000027        -1  auto_c_000000037         1
    table_1_1_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_1_5         auto_c_000000047         1  auto_c_000000087         1
    table_1_1_5         auto_c_000000104         1  auto_c_000000147        -7
    table_1_1_6         auto_c_000000003        -3  auto_c_000000011         1
    table_1_1_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_2_0         auto_c_000000003        -4  auto_c_000000007        -1
    table_1_2_0         auto_c_000000015         1  auto_c_000000032         1
    table_1_2_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_2_0         auto_c_000000047         1  auto_c_000000079         1
    table_1_2_0         auto_c_000000088         1  auto_c_000000148        -7
    table_1_2_1         auto_c_000000003        -1  auto_c_000000011        -1
    table_1_2_1         auto_c_000000015         1  auto_c_000000033         1
    table_1_2_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_2_1         auto_c_000000047         1  auto_c_000000084         1
    table_1_2_1         auto_c_000000089         1  auto_c_000000149        -7
    table_1_2_2         auto_c_000000014         1  auto_c_000000034         1
    table_1_2_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_2_2         auto_c_000000047         1
    table_1_2_3         auto_c_000000003        -5  auto_c_000000015         1
    table_1_2_3         auto_c_000000019        -1  auto_c_000000035         1
    table_1_2_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_2_3         auto_c_000000047         1  auto_c_000000090         1
    table_1_2_3         auto_c_000000095         1  auto_c_000000150        -7
    table_1_2_4         auto_c_000000003        -6  auto_c_000000015         1
    table_1_2_4         auto_c_000000023        -1  auto_c_000000036         1
    table_1_2_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_2_4         auto_c_000000047         1  auto_c_000000091         1
    table_1_2_4         auto_c_000000100         1  auto_c_000000151        -7
    table_1_2_5         auto_c_000000003        -6  auto_c_000000015         1
    table_1_2_5         auto_c_000000027        -1  auto_c_000000037         1
    table_1_2_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_2_5         auto_c_000000047         1  auto_c_000000092         1
    table_1_2_5         auto_c_000000105         1  auto_c_000000152        -7
    table_1_2_6         auto_c_000000003        -4  auto_c_000000015         1
    table_1_2_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_3_0         auto_c_000000003        -4  auto_c_000000007        -1
    table_1_3_0         auto_c_000000019         1  auto_c_000000032         1
    table_1_3_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_3_0         auto_c_000000047         1  auto_c_000000080         1
    table_1_3_0         auto_c_000000093         1  auto_c_000000153        -7
    table_1_3_1         auto_c_000000003        -4  auto_c_000000011        -1
    table_1_3_1         auto_c_000000019         1  auto_c_000000033         1
    table_1_3_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_3_1         auto_c_000000047         1  auto_c_000000085         1
    table_1_3_1         auto_c_000000094         1  auto_c_000000154        -7
    table_1_3_2         auto_c_000000003        -5  auto_c_000000015        -1
    table_1_3_2         auto_c_000000019         1  auto_c_000000034         1
    table_1_3_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_3_2         auto_c_000000047         1  auto_c_000000090         1
    table_1_3_2         auto_c_000000095         1  auto_c_000000155        -7
    table_1_3_3         auto_c_000000018         1  auto_c_000000035         1
    table_1_3_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_3_3         auto_c_000000047         1
    table_1_3_4         auto_c_000000003        -3  auto_c_000000019         1
    table_1_3_4         auto_c_000000023        -1  auto_c_000000036         1
    table_1_3_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_3_4         auto_c_000000047         1  auto_c_000000096         1
    table_1_3_4         auto_c_000000101         1  auto_c_000000156        -7
    table_1_3_5         auto_c_000000003        -3  auto_c_000000019         1
    table_1_3_5         auto_c_000000027        -1  auto_c_000000037         1
    table_1_3_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_3_5         auto_c_000000047         1  auto_c_000000097         1
    table_1_3_5         auto_c_000000106         1  auto_c_000000157        -7
    table_1_3_6         auto_c_000000003        -2  auto_c_000000019         1
    table_1_3_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_4_0         auto_c_000000003        -6  auto_c_000000007        -1
    table_1_4_0         auto_c_000000023         1  auto_c_000000032         1
    table_1_4_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_4_0         auto_c_000000047         1  auto_c_000000081         1
    table_1_4_0         auto_c_000000098         1  auto_c_000000158        -7
    table_1_4_1         auto_c_000000003        -7  auto_c_000000011        -1
    table_1_4_1         auto_c_000000023         1  auto_c_000000033         1
    table_1_4_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_4_1         auto_c_000000047         1  auto_c_000000086         1
    table_1_4_1         auto_c_000000099         1  auto_c_000000159        -7
    table_1_4_2         auto_c_000000003        -8  auto_c_000000015        -1
    table_1_4_2         auto_c_000000023         1  auto_c_000000034         1
    table_1_4_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_4_2         auto_c_000000047         1  auto_c_000000091         1
    table_1_4_2         auto_c_000000100         1  auto_c_000000160        -7
    table_1_4_3         auto_c_000000003        -3  auto_c_000000019        -1
    table_1_4_3         auto_c_000000023         1  auto_c_000000035         1
    table_1_4_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_4_3         auto_c_000000047         1  auto_c_000000096         1
    table_1_4_3         auto_c_000000101         1  auto_c_000000161        -7
    table_1_4_4         auto_c_000000022         1  auto_c_000000036         1
    table_1_4_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_4_4         auto_c_000000047         1
    table_1_4_5         auto_c_000000003        -2  auto_c_000000023         1
    table_1_4_5         auto_c_000000027        -1  auto_c_000000037         1
    table_1_4_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_4_5         auto_c_000000047         1  auto_c_000000102         1
    table_1_4_5         auto_c_000000107         1  auto_c_000000162        -7
    table_1_4_6         auto_c_000000003        -4  auto_c_000000023         1
    table_1_4_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_5_0         auto_c_000000003        -6  auto_c_000000007        -1
    table_1_5_0         auto_c_000000027         1  auto_c_000000032         1
    table_1_5_0         auto_c_000000045         3  auto_c_000000046         1
    table_1_5_0         auto_c_000000047         1  auto_c_000000082         1
    table_1_5_0         auto_c_000000103         1  auto_c_000000163        -7
    table_1_5_1         auto_c_000000003        -7  auto_c_000000011        -1
    table_1_5_1         auto_c_000000027         1  auto_c_000000033         1
    table_1_5_1         auto_c_000000045         2  auto_c_000000046         1
    table_1_5_1         auto_c_000000047         1  auto_c_000000087         1
    table_1_5_1         auto_c_000000104         1  auto_c_000000164        -7
    table_1_5_2         auto_c_000000003        -8  auto_c_000000015        -1
    table_1_5_2         auto_c_000000027         1  auto_c_000000034         1
    table_1_5_2         auto_c_000000045         6  auto_c_000000046         1
    table_1_5_2         auto_c_000000047         1  auto_c_000000092         1
    table_1_5_2         auto_c_000000105         1  auto_c_000000165        -7
    table_1_5_3         auto_c_000000003        -3  auto_c_000000019        -1
    table_1_5_3         auto_c_000000027         1  auto_c_000000035         1
    table_1_5_3         auto_c_000000045         5  auto_c_000000046         1
    table_1_5_3         auto_c_000000047         1  auto_c_000000097         1
    table_1_5_3         auto_c_000000106         1  auto_c_000000166        -7
    table_1_5_4         auto_c_000000003        -2  auto_c_000000023        -1
    table_1_5_4         auto_c_000000027         1  auto_c_000000036         1
    table_1_5_4         auto_c_000000045         4  auto_c_000000046         1
    table_1_5_4         auto_c_000000047         1  auto_c_000000102         1
    table_1_5_4         auto_c_000000107         1  auto_c_000000167        -7
    table_1_5_5         auto_c_000000026         1  auto_c_000000037         1
    table_1_5_5         auto_c_000000045         4  auto_c_000000046         1
    table_1_5_5         auto_c_000000047         1
    table_1_5_6         auto_c_000000003        -4  auto_c_000000027         1
    table_1_5_6         auto_c_000000031        -1  auto_c_000000044         1
    table_1_6_0         auto_c_000000003        -2  auto_c_000000007        -1
    table_1_6_0         auto_c_000000031         1  auto_c_000000032         1
    table_1_6_0         auto_c_000000043         1  auto_c_000000045         3
    table_1_6_0         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_1         auto_c_000000003        -3  auto_c_000000011        -1
    table_1_6_1         auto_c_000000031         1  auto_c_000000033         1
    table_1_6_1         auto_c_000000043         1  auto_c_000000045         2
    table_1_6_1         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_2         auto_c_000000003        -4  auto_c_000000015        -1
    table_1_6_2         auto_c_000000031         1  auto_c_000000034         1
    table_1_6_2         auto_c_000000043         1  auto_c_000000045         6
    table_1_6_2         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_3         auto_c_000000003        -3  auto_c_000000019        -1
    table_1_6_3         auto_c_000000031         1  auto_c_000000035         1
    table_1_6_3         auto_c_000000043         1  auto_c_000000045         5
    table_1_6_3         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_4         auto_c_000000003        -4  auto_c_000000023        -1
    table_1_6_4         auto_c_000000031         1  auto_c_000000036         1
    table_1_6_4         auto_c_000000043         1  auto_c_000000045         4
    table_1_6_4         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_5         auto_c_000000003        -4  auto_c_000000027        -1
    table_1_6_5         auto_c_000000031         1  auto_c_000000037         1
    table_1_6_5         auto_c_000000043         1  auto_c_000000045         4
    table_1_6_5         auto_c_000000046         1  auto_c_000000047         1
    table_1_6_6         auto_c_000000030         1
    u_0_0               auto_c_000000108        -1  auto_c_000000109        -1
    u_0_0               auto_c_000000110        -1  auto_c_000000111        -1
    u_0_0               auto_c_000000112        -1  auto_c_000000113         1
    u_0_0               auto_c_000000118         1  auto_c_000000123         1
    u_0_0               auto_c_000000128         1  auto_c_000000133         1
    u_0_1               auto_c_000000108         1  auto_c_000000113        -1
    u_0_1               auto_c_000000114        -1  auto_c_000000115        -1
    u_0_1               auto_c_000000116        -1  auto_c_000000117        -1
    u_0_1               auto_c_000000119         1  auto_c_000000124         1
    u_0_1               auto_c_000000129         1  auto_c_000000134         1
    u_0_2               auto_c_000000109         1  auto_c_000000114         1
    u_0_2               auto_c_000000118        -1  auto_c_000000119        -1
    u_0_2               auto_c_000000120        -1  auto_c_000000121        -1
    u_0_2               auto_c_000000122        -1  auto_c_000000125         1
    u_0_2               auto_c_000000130         1  auto_c_000000135         1
    u_0_3               auto_c_000000110         1  auto_c_000000115         1
    u_0_3               auto_c_000000120         1  auto_c_000000123        -1
    u_0_3               auto_c_000000124        -1  auto_c_000000125        -1
    u_0_3               auto_c_000000126        -1  auto_c_000000127        -1
    u_0_3               auto_c_000000131         1  auto_c_000000136         1
    u_0_4               auto_c_000000111         1  auto_c_000000116         1
    u_0_4               auto_c_000000121         1  auto_c_000000126         1
    u_0_4               auto_c_000000128        -1  auto_c_000000129        -1
    u_0_4               auto_c_000000130        -1  auto_c_000000131        -1
    u_0_4               auto_c_000000132        -1  auto_c_000000137         1
    u_0_5               auto_c_000000112         1  auto_c_000000117         1
    u_0_5               auto_c_000000122         1  auto_c_000000127         1
    u_0_5               auto_c_000000132         1  auto_c_000000133        -1
    u_0_5               auto_c_000000134        -1  auto_c_000000135        -1
    u_0_5               auto_c_000000136        -1  auto_c_000000137        -1
    u_1_0               auto_c_000000138        -1  auto_c_000000139        -1
    u_1_0               auto_c_000000140        -1  auto_c_000000141        -1
    u_1_0               auto_c_000000142        -1  auto_c_000000143         1
    u_1_0               auto_c_000000148         1  auto_c_000000153         1
    u_1_0               auto_c_000000158         1  auto_c_000000163         1
    u_1_1               auto_c_000000138         1  auto_c_000000143        -1
    u_1_1               auto_c_000000144        -1  auto_c_000000145        -1
    u_1_1               auto_c_000000146        -1  auto_c_000000147        -1
    u_1_1               auto_c_000000149         1  auto_c_000000154         1
    u_1_1               auto_c_000000159         1  auto_c_000000164         1
    u_1_2               auto_c_000000139         1  auto_c_000000144         1
    u_1_2               auto_c_000000148        -1  auto_c_000000149        -1
    u_1_2               auto_c_000000150        -1  auto_c_000000151        -1
    u_1_2               auto_c_000000152        -1  auto_c_000000155         1
    u_1_2               auto_c_000000160         1  auto_c_000000165         1
    u_1_3               auto_c_000000140         1  auto_c_000000145         1
    u_1_3               auto_c_000000150         1  auto_c_000000153        -1
    u_1_3               auto_c_000000154        -1  auto_c_000000155        -1
    u_1_3               auto_c_000000156        -1  auto_c_000000157        -1
    u_1_3               auto_c_000000161         1  auto_c_000000166         1
    u_1_4               auto_c_000000141         1  auto_c_000000146         1
    u_1_4               auto_c_000000151         1  auto_c_000000156         1
    u_1_4               auto_c_000000158        -1  auto_c_000000159        -1
    u_1_4               auto_c_000000160        -1  auto_c_000000161        -1
    u_1_4               auto_c_000000162        -1  auto_c_000000167         1
    u_1_5               auto_c_000000142         1  auto_c_000000147         1
    u_1_5               auto_c_000000152         1  auto_c_000000157         1
    u_1_5               auto_c_000000162         1  auto_c_000000163        -1
    u_1_5               auto_c_000000164        -1  auto_c_000000165        -1
    u_1_5               auto_c_000000166        -1  auto_c_000000167        -1
    obj                 COST                     1  auto_c_000000000         1
    obj                 auto_c_000000001         1  auto_c_000000002         1
    obj                 auto_c_000000003         1
  INTEND    'MARKER'                            'INTEND'
RHS
    RHS                 auto_c_000000000        32  auto_c_000000001         8
    RHS                 auto_c_000000002         0  auto_c_000000003         0
    RHS                 auto_c_000000004         0  auto_c_000000005         0
    RHS                 auto_c_000000006         0  auto_c_000000007         0
    RHS                 auto_c_000000008         0  auto_c_000000009         0
    RHS                 auto_c_000000010         0  auto_c_000000011         0
    RHS                 auto_c_000000012         0  auto_c_000000013         0
    RHS                 auto_c_000000014         0  auto_c_000000015         0
    RHS                 auto_c_000000016         0  auto_c_000000017         0
    RHS                 auto_c_000000018         0  auto_c_000000019         0
    RHS                 auto_c_000000020         0  auto_c_000000021         0
    RHS                 auto_c_000000022         0  auto_c_000000023         0
    RHS                 auto_c_000000024         0  auto_c_000000025         0
    RHS                 auto_c_000000026         0  auto_c_000000027         0
    RHS                 auto_c_000000028         0  auto_c_000000029         0
    RHS                 auto_c_000000030         0  auto_c_000000031         0
    RHS                 auto_c_000000032         1  auto_c_000000033         1
    RHS                 auto_c_000000034         1  auto_c_000000035         1
    RHS                 auto_c_000000036         1  auto_c_000000037         1
    RHS                 auto_c_000000038         1  auto_c_000000039         1
    RHS                 auto_c_000000040        10  auto_c_000000041         2
    RHS                 auto_c_000000042        32  auto_c_000000043         1
    RHS                 auto_c_000000044         1  auto_c_000000045        15
    RHS                 auto_c_000000046         2  auto_c_000000047        32
    RHS                 auto_c_000000048         1  auto_c_000000049         1
    RHS                 auto_c_000000050         1  auto_c_000000051         1
    RHS                 auto_c_000000052         1  auto_c_000000053         1
    RHS                 auto_c_000000054         1  auto_c_000000055         1
    RHS                 auto_c_000000056         1  auto_c_000000057         1
    RHS                 auto_c_000000058         1  auto_c_000000059         1
    RHS                 auto_c_000000060         1  auto_c_000000061         1
    RHS                 auto_c_000000062         1  auto_c_000000063         1
    RHS                 auto_c_000000064         1  auto_c_000000065         1
    RHS                 auto_c_000000066         1  auto_c_000000067         1
    RHS                 auto_c_000000068         1  auto_c_000000069         1
    RHS                 auto_c_000000070         1  auto_c_000000071         1
    RHS                 auto_c_000000072         1  auto_c_000000073         1
    RHS                 auto_c_000000074         1  auto_c_000000075         1
    RHS                 auto_c_000000076         1  auto_c_000000077         1
    RHS                 auto_c_000000078         1  auto_c_000000079         1
    RHS                 auto_c_000000080         1  auto_c_000000081         1
    RHS                 auto_c_000000082         1  auto_c_000000083         1
    RHS                 auto_c_000000084         1  auto_c_000000085         1
    RHS                 auto_c_000000086         1  auto_c_000000087         1
    RHS                 auto_c_000000088         1  auto_c_000000089         1
    RHS                 auto_c_000000090         1  auto_c_000000091         1
    RHS                 auto_c_000000092         1  auto_c_000000093         1
    RHS                 auto_c_000000094         1  auto_c_000000095         1
    RHS                 auto_c_000000096         1  auto_c_000000097         1
    RHS                 auto_c_000000098         1  auto_c_000000099         1
    RHS                 auto_c_000000100         1  auto_c_000000101         1
    RHS                 auto_c_000000102         1  auto_c_000000103         1
    RHS                 auto_c_000000104         1  auto_c_000000105         1
    RHS                 auto_c_000000106         1  auto_c_000000107         1
    RHS                 auto_c_000000108        -6  auto_c_000000109        -6
    RHS                 auto_c_000000110        -6  auto_c_000000111        -6
    RHS                 auto_c_000000112        -6  auto_c_000000113        -6
    RHS                 auto_c_000000114        -6  auto_c_000000115        -6
    RHS                 auto_c_000000116        -6  auto_c_000000117        -6
    RHS                 auto_c_000000118        -6  auto_c_000000119        -6
    RHS                 auto_c_000000120        -6  auto_c_000000121        -6
    RHS                 auto_c_000000122        -6  auto_c_000000123        -6
    RHS                 auto_c_000000124        -6  auto_c_000000125        -6
    RHS                 auto_c_000000126        -6  auto_c_000000127        -6
    RHS                 auto_c_000000128        -6  auto_c_000000129        -6
    RHS                 auto_c_000000130        -6  auto_c_000000131        -6
    RHS                 auto_c_000000132        -6  auto_c_000000133        -6
    RHS                 auto_c_000000134        -6  auto_c_000000135        -6
    RHS                 auto_c_000000136        -6  auto_c_000000137        -6
    RHS                 auto_c_000000138        -6  auto_c_000000139        -6
    RHS                 auto_c_000000140        -6  auto_c_000000141        -6
    RHS                 auto_c_000000142        -6  auto_c_000000143        -6
    RHS                 auto_c_000000144        -6  auto_c_000000145        -6
    RHS                 auto_c_000000146        -6  auto_c_000000147        -6
    RHS                 auto_c_000000148        -6  auto_c_000000149        -6
    RHS                 auto_c_000000150        -6  auto_c_000000151        -6
    RHS                 auto_c_000000152        -6  auto_c_000000153        -6
    RHS                 auto_c_000000154        -6  auto_c_000000155        -6
    RHS                 auto_c_000000156        -6  auto_c_000000157        -6
    RHS                 auto_c_000000158        -6  auto_c_000000159        -6
    RHS                 auto_c_000000160        -6  auto_c_000000161        -6
    RHS                 auto_c_000000162        -6  auto_c_000000163        -6
    RHS                 auto_c_000000164        -6  auto_c_000000165        -6
    RHS                 auto_c_000000166        -6  auto_c_000000167        -6
BOUNDS
 BV BOUND               table_0_0_0
 BV BOUND               table_0_0_1
 BV BOUND               table_0_0_2
 BV BOUND               table_0_0_3
 BV BOUND               table_0_0_4
 BV BOUND               table_0_0_5
 BV BOUND               table_0_0_6
 BV BOUND               table_0_1_0
 BV BOUND               table_0_1_1
 BV BOUND               table_0_1_2
 BV BOUND               table_0_1_3
 BV BOUND               table_0_1_4
 BV BOUND               table_0_1_5
 BV BOUND               table_0_1_6
 BV BOUND               table_0_2_0
 BV BOUND               table_0_2_1
 BV BOUND               table_0_2_2
 BV BOUND               table_0_2_3
 BV BOUND               table_0_2_4
 BV BOUND               table_0_2_5
 BV BOUND               table_0_2_6
 BV BOUND               table_0_3_0
 BV BOUND               table_0_3_1
 BV BOUND               table_0_3_2
 BV BOUND               table_0_3_3
 BV BOUND               table_0_3_4
 BV BOUND               table_0_3_5
 BV BOUND               table_0_3_6
 BV BOUND               table_0_4_0
 BV BOUND               table_0_4_1
 BV BOUND               table_0_4_2
 BV BOUND               table_0_4_3
 BV BOUND               table_0_4_4
 BV BOUND               table_0_4_5
 BV BOUND               table_0_4_6
 BV BOUND               table_0_5_0
 BV BOUND               table_0_5_1
 BV BOUND               table_0_5_2
 BV BOUND               table_0_5_3
 BV BOUND               table_0_5_4
 BV BOUND               table_0_5_5
 BV BOUND               table_0_5_6
 BV BOUND               table_0_6_0
 BV BOUND               table_0_6_1
 BV BOUND               table_0_6_2
 BV BOUND               table_0_6_3
 BV BOUND               table_0_6_4
 BV BOUND               table_0_6_5
 BV BOUND               table_0_6_6
 BV BOUND               table_1_0_0
 BV BOUND               table_1_0_1
 BV BOUND               table_1_0_2
 BV BOUND               table_1_0_3
 BV BOUND               table_1_0_4
 BV BOUND               table_1_0_5
 BV BOUND               table_1_0_6
 BV BOUND               table_1_1_0
 BV BOUND               table_1_1_1
 BV BOUND               table_1_1_2
 BV BOUND               table_1_1_3
 BV BOUND               table_1_1_4
 BV BOUND               table_1_1_5
 BV BOUND               table_1_1_6
 BV BOUND               table_1_2_0
 BV BOUND               table_1_2_1
 BV BOUND               table_1_2_2
 BV BOUND               table_1_2_3
 BV BOUND               table_1_2_4
 BV BOUND               table_1_2_5
 BV BOUND               table_1_2_6
 BV BOUND               table_1_3_0
 BV BOUND               table_1_3_1
 BV BOUND               table_1_3_2
 BV BOUND               table_1_3_3
 BV BOUND               table_1_3_4
 BV BOUND               table_1_3_5
 BV BOUND               table_1_3_6
 BV BOUND               table_1_4_0
 BV BOUND               table_1_4_1
 BV BOUND               table_1_4_2
 BV BOUND               table_1_4_3
 BV BOUND               table_1_4_4
 BV BOUND               table_1_4_5
 BV BOUND               table_1_4_6
 BV BOUND               table_1_5_0
 BV BOUND               table_1_5_1
 BV BOUND               table_1_5_2
 BV BOUND               table_1_5_3
 BV BOUND               table_1_5_4
 BV BOUND               table_1_5_5
 BV BOUND               table_1_5_6
 BV BOUND               table_1_6_0
 BV BOUND               table_1_6_1
 BV BOUND               table_1_6_2
 BV BOUND               table_1_6_3
 BV BOUND               table_1_6_4
 BV BOUND               table_1_6_5
 BV BOUND               table_1_6_6
 UI BOUND               courier_distance_0      32
 UI BOUND               courier_distance_1      32
 UI BOUND               u_0_0                    6
 UI BOUND               u_0_1                    6
 UI BOUND               u_0_2                    6
 UI BOUND               u_0_3                    6
 UI BOUND               u_0_4                    6
 UI BOUND               u_0_5                    6
 UI BOUND               u_0_6                    6
 UI BOUND               u_1_0                    6
 UI BOUND               u_1_1                    6
 UI BOUND               u_1_2                    6
 UI BOUND               u_1_3                    6
 UI BOUND               u_1_4                    6
 UI BOUND               u_1_5                    6
 UI BOUND               u_1_6                    6
 UI BOUND               obj                     32
ENDATA
